local Translations = {
["<b>This will make larger killers (ex. Sixer) see-through while you are a killer.</b>"] = "<b>这会让大型杀手（例如 Sixer）在你作为杀手时变得透明。</b>",
["<b>WARNING: Even with this enabled, it's still recommended to avoid playing if you're epileptic!</b>"] = "<b>警告：即使启用了此功能，如果您患有癫痫，仍建议避免游戏！</b>",
["<b>WARNING: Even with this setting, it is NOT advised to play the game if you have sensitive hearing!</b>"] = "<b>警告：即使启用了此设置，如果您听力敏感，仍不建议游玩！</b>",
["<b>Will cause slight lagspikes when revealing Auras if enabled. Only activate if your device is old & if you cannot regularly see the Auras of players/objects</b>"] = "<b>启用后，显示光环时可能会导致轻微卡顿。仅当您的设备较旧且无法正常看到玩家/物体的光环时再开启</b>",
[">"] = ">",
["??? - I Love TV"] = "??? - 我爱电视",
["A Captain and his Ship"] = "船长与他的船",
["ABC"] = "ABC",
["AFK Farming"] = "挂机刷取",
["AFK Mode"] = "挂机模式",
["AFK mode is on. While enabled, you will be kept from being put ingame every time a match starts.\nAFK mode can be toggled on/off in the settings menu and in the lobby through talking to the grandfather clock."] = "挂机模式已开启。启用后，每次比赛开始时你将不会被放入游戏中。\n你可以在设置菜单中或在大厅通过与祖父钟对话来切换挂机模式的开启/关闭。",
["Absolvement"] = "赦免",
["Accessibility"] = "无障碍",
["Accumulated Hitmarkers"] = "累计命中标记",
["Achievements"] = "成就",
["Achievements -- 3/101 Unlocked"] = "成就 -- 3/101 已解锁",
["Actual Noob"] = "真正的菜鸟",
["Admin Noli (Skin)"] = "管理员 Noli（皮肤）",
["Advanced / Dev"] = "高级 / 开发者",
["Aim Behavior"] = "瞄准行为",
["Aim Duration (seconds)"] = "瞄准持续时间（秒）",
["Aim Key"] = "瞄准键",
["Aim Punch"] = "瞄准冲击",
["Aim Snap Delay (s)"] = "瞄准吸附延迟（秒）",
["Aim up/down for slopes and platforms"] = "为斜坡和平台上下瞄准",
["Aimbot"] = "自瞄",
["Aimbot Type"] = "自瞄类型",
["All"] = "全部",
["All Ur Base Are Belong 2 Me"] = "你们所有基地都属于我",
["Alt + Tab"] = "Alt + Tab",
["Alt Ability 1 Keybind"] = "备用技能 1 键位",
["Alt Ability 2 Keybind"] = "备用技能 2 键位",
["Alt Ability 3 Keybind"] = "备用技能 3 键位",
["Alt Ability 4 Keybind"] = "备用技能 4 键位",
["Ambience by: "] = "环境音效由：",
["Animation ID"] = "动画 ID",
["Anti Bait"] = "反诱饵",
["Anti-Backstab"] = "反背刺",
["Anti-Bait Hold (x0.01s)"] = "反诱饵保持（x0.01秒）",
["Aortic Work Of Art"] = "主动脉艺术品",
["Arc Segments"] = "弧线段数",
["As 007n7, successfully teleport with c00lgui while the Killer is less than 12 studs away from you"] = "作为 007n7，当杀手距离你小于 12 个长度单位时，使用 c00lgui 成功传送",
["As 007n7, trick the Killer into killing your clone"] = "作为 007n7，欺骗杀手杀死你的克隆体",
["As 007n7, use c00lgui to teleport directly to the Killer"] = "作为 007n7，使用 c00lgui 直接传送到杀手所在位置",
["As 1x1x1x1, kill 50 Shedletskys"] = "作为 1x1x1x1，杀死 50 个 Shedletsky",
["As Builderman, keep a Dispenser alive for more than 120 seconds"] = "作为 Builderman，让补给器存活超过 120 秒",
["As CI Slasher, kill 75 Survivors."] = "作为 CI Slasher，杀死 75 名幸存者。",
["As Chance, die from your flintlock blowing up on you"] = "作为 Chance，死于自己的燧发枪爆炸",
["As Chance, have your coin land on heads 5 times in a row"] = "作为 Chance，连续 5 次掷硬币正面朝上",
["As Chance, hit the Killer and 2 of their Minions in the same shot"] = "作为 Chance，一枪同时击中杀手及其 2 个随从",
["As Chance, keep using your coin flip ability until you gain 50 stacks of Weakness"] = "作为 Chance，不断使用掷硬币技能直到获得 50 层虚弱",
["As Chance, make a successful coin flip & then shoot at a Killer within 10 seconds"] = "作为 Chance，成功掷硬币后在 10 秒内向杀手开枪",
["As Chance, stun the Killer by blowing up your own flintlock"] = "作为 Chance，用自己燧发枪的爆炸击晕杀手",
["As Dusekkar, shield a Survivor from lethal damage."] = "作为 Dusekkar，为一名幸存者抵挡致命伤害。",
["As Elliot, give a Pizza to 007n7"] = "作为 Elliot，给 007n7 一个披萨",
["As Elliot, throw your pizza at the Killer"] = "作为 Elliot，向杀手扔披萨",
["As Guest 1337, block an otherwise lethal attack as the Last Survivor Standing, and win"] = "作为 Guest 1337，作为最后幸存的幸存者格挡住一次致命攻击并获胜",
["As Guest 1337, successfully block a Killer's attack 3 times in a row"] = "作为 Guest 1337，连续成功格挡杀手的攻击 3 次",
["As Guest 1337, successfully block a Killer's attack and then land a punch on them right after"] = "作为 Guest 1337，成功格挡杀手攻击后立即对其出拳",
["As Guest 1337, successfully punch a Killer while falling"] = "作为 Guest 1337，在下落过程中成功击打杀手",
["As Guest 666, kill a Survivor using Infernal Cry in Blood Hunt"] = "作为 Guest 666，在血猎中使用地狱尖啸杀死一名幸存者",
["As Guest 666, land a fully charged Demonic Pursuit on a Survivor repairing a Generator"] = "作为 Guest 666，用完全蓄力的恶魔追击命中正在修理发电机的幸存者",
["As Guest 666, use Blood Hunt with 6 seconds or less remaining"] = "作为 Guest 666，在剩余 6 秒或更少时使用血猎",
["As Jane, Purify 3 Survivors with one use of Crystal Pitch"] = "作为 Jane，一次使用水晶投掷净化 3 名幸存者",
["As Jane, hit a killer from 110+ studs away"] = "作为 Jane，从 110 多个长度单位外击中杀手",
["As Jane, hit a level 3 Hatchet stun."] = "作为 Jane，命中 3 级手斧眩晕。",
["As John Doe, kill a Survivor with one of your spikes"] = "作为 John Doe，用你的尖刺杀死一名幸存者",
["As Noli, Kill 33 Admins"] = "作为 Noli，杀死 33 个管理员",
["As Noli, Void Rush into a charging Guest 1337 (or vice versa)"] = "作为 Noli，虚空冲锋撞上正在冲锋的 Guest 1337（反之亦然）",
["As Noli, hit 5 Survivors in a single Void Rush"] = "作为 Noli，一次虚空冲锋命中 5 名幸存者",
["As Noli, trick a Sentinel into stunning your Mirage"] = "作为 Noli，诱骗哨兵击晕你的幻影",
["As Noob, attempt to use Bloxy Cola while under the effects of Slateskin"] = "作为 Noob，在石板皮肤效果下尝试使用 Bloxy Cola",
["As Noob, drink 2 Bloxy Colas within the same 30 seconds."] = "作为 Noob，在同一 30 秒内喝 2 瓶 Bloxy Cola。",
["As Noob, run as far as possible with one Bloxy Cola"] = "作为 Noob，用一瓶 Bloxy Cola 跑尽可能远的距离",
["As Noob, use the Ghostburger to hide from the Killer or their minions"] = "作为 Noob，使用幽灵汉堡躲避杀手或其随从",
["As Nosferatu, hit 3 Survivors in one use of Cataclysm"] = "作为 Nosferatu，一次大灾变命中 3 名幸存者",
["As Nosferatu, hit a Survivor with Bloodhook from more than 90 studs away, and successfully reel them in"] = "作为 Nosferatu，从 90 多个长度单位外使用血钩命中幸存者并成功将其拉回",
["As Shedletsky, get caught eating your fried chicken by the Killer"] = "作为 Shedletsky，被杀手抓到在吃炸鸡",
["As Shedletsky, stun the Killer at least 3 times in one round"] = "作为 Shedletsky，在一回合中至少击晕杀手 3 次",
["As Slasher, Kill a Survivor with the First Hit of Gashing Wound near a Taph Subspace Tripmine"] = "作为 Slasher，在 Taph 的子空间绊雷附近用裂伤的第一击杀死幸存者",
["As Slasher, kill a Survivor with Behead"] = "作为 Slasher，用斩首杀死幸存者",
["As Taph, be the last survivor standing"] = "作为 Taph，成为最后存活的幸存者",
["As Two Time, die within the first 10 seconds of gaining your second chance"] = "作为 Two Time，在获得第二次机会后的前 10 秒内死亡",
["As Two Time, respawn less than 16 studs away from where you initially died"] = "作为 Two Time，在距离初始死亡地点不到 16 个长度单位处重生",
["As a Survivor, win a round without getting injured once"] = "作为幸存者，一局中未受一次伤获胜",
["As a Survivor, win a round without the use of any of your abilities"] = "作为幸存者，未使用任何技能获胜",
["As a survivor, ask for help from a Support class survivor 8 times whilst fully healed in one round."] = "作为幸存者，在一局中满血状态下向支援类幸存者求助 8 次。",
["As c00lkidd, hit two or more Survivors with one projectile"] = "作为 c00lkidd，一发投射物命中两名或以上幸存者",
["As c00lkidd, kill an Elliot with a Pizza Delivery minion"] = "作为 c00lkidd，用披萨配送随从杀死 Elliot",
["As the Killer, win a round without the use of any of your abilities excluding your main ability"] = "作为杀手，除主要技能外不使用任何技能获胜",
["At 70% health or above, steal a pizza from someone below 25% health, or under the same conditions have it stolen from you."] = "在生命值 70% 或以上时，从生命值低于 25% 的人那里偷披萨，或在相同条件下被偷走披萨。",
["At What Cost"] = "代价为何",
["Audio"] = "音频",
["Auto Backstab"] = "自动背刺",
["Auto Block"] = "自动格挡",
["Auto Block Radius"] = "自动格挡半径",
["Auto Punch"] = "自动出拳",
["Auto Solve"] = "自动解谜",
["Auto Stab on Backstab"] = "背刺时自动捅刺",
["Auto-Play on LMS"] = "最后幸存者阶段自动游玩",
["Awaiting ServerList from API..."] = "正在从 API 等待服务器列表...",
["Backstab"] = "背刺",
["Backstab Type"] = "背刺类型",
["Ban Evasion"] = "封禁逃避",
["Behind"] = "背后",
["Behind Distance"] = "背后距离",
["Better Detection"] = "更好的检测",
["Better Luck Next Time"] = "下次运气更好",
["Birinbirin9"] = "Birinbirin9",
["Black disc + red glow"] = "黑色圆盘 + 红色光晕",
["Black, White, and Gray."] = "黑、白、灰。",
["Blacklisted Customer"] = "黑名单客户",
["Blame John!"] = "都怪 John！",
["Blatant Speed"] = "明显速度",
["Block Cooldown Checker"] = "格挡冷却检查器",
["Block Delay"] = "格挡延迟",
["Block Delay (x0.05s)"] = "格挡延迟（x0.05秒）",
["Bloodbath"] = "血浴",
["Bloxy Cola"] = "Bloxy 可乐",
["Brutality"] = "残暴",
["Bug Abuse"] = "漏洞滥用",
["Buildings"] = "建筑物",
["Built by: doczotic and pluto"] = "由 doczotic 和 pluto 构建",
["ButtonB"] = "按钮 B",
["ButtonL1"] = "按钮 L1",
["ButtonL2"] = "按钮 L2",
["ButtonL3"] = "按钮 L3",
["ButtonR1"] = "按钮 R1",
["ButtonR2"] = "按钮 R2",
["ButtonX"] = "按钮 X",
["ButtonY"] = "按钮 Y",
["CRAZZZYYY EIGHTS"] = "疯 狂 八 八 八",
["Camera Sway Amount"] = "相机晃动幅度",
["Cancel"] = "取消",
["Caps velocity to known killer run speed"] = "将速度上限限制为已知杀手奔跑速度",
["Center Stamina Counter"] = "居中体力计数器",
["Certain sound effects will switch based on your selected pronouns when using a cosplay skin."] = "使用角色扮演皮肤时，某些音效会根据你选择的人称代词切换。",
["Challenges"] = "挑战",
["Chance"] = "Chance",
["Chance Aimbot"] = "Chance 自瞄",
["Chance Time"] = "Chance 时间",
["Chance to Become Killer: 10.5"] = "成为杀手的几率：10.5",
["Chance to Become Killer: 9.5"] = "成为杀手的几率：9.5",
["Character"] = "角色",
["Charge Control"] = "蓄力控制",
["Charge Speed Cap"] = "蓄力速度上限",
["Charge Speed Limit"] = "蓄力速度限制",
["Cinematic Text"] = "电影式文字",
["Click on a button"] = "点击按钮",
["Close Enough To Be A Reference I Guess"] = "我想这已经足够作为参考了",
["Close UI"] = "关闭界面",
["Close Window"] = "关闭窗口",
["Cola Addiction"] = "可乐成瘾",
["Coldhearted I"] = "冷酷无情 I",
["Coldhearted II"] = "冷酷无情 II",
["Coldhearted III"] = "冷酷无情 III",
["Coldhearted IV"] = "冷酷无情 IV",
["Coldhearted V"] = "冷酷无情 V",
["Color Guide"] = "颜色指南",
["Combat Initiated"] = "战斗开始",
["Coming straight from YOUR house."] = "直接从你家来的。",
["Complete the puzzles on each generator to get them up & running. (0/5)\nSurvive until the timer runs out."] = "完成每个发电机上的谜题使其启动并运行。（0/5）\n存活直到计时器结束。",
["Completionist"] = "完美主义者",
["CondemnedLMS"] = "CondemnedLMS",
["Console"] = "控制台",
["Cooldown (s)"] = "冷却时间（秒）",
["Coolest Kid In Town"] = "镇上最酷的孩子",
["Core Block"] = "核心格挡",
["Credits"] = "致谢",
["Crosshair Enabled"] = "启用准星",
["Crosshair ID"] = "准星 ID",
["Currency"] = "货币",
["Current Value"] = "当前数值",
["Custom Punch Sound ID"] = "自定义出拳音效 ID",
["Custom Shoot Anim"] = "自定义射击动画",
["Custom Stamina"] = "自定义体力",
["Customization"] = "自定义",
["DEAD"] = "已死亡",
["DEFAULT"] = "默认",
["DOWNN INNN FRONTTTTT"] = "前 前 前 前 方",
["DPadDown"] = "方向键下",
["Dead Ringer"] = "死亡钟声",
["Death Of Roblox (Real)"] = "Roblox 之死（真实）",
["Deodorant"] = "除臭剂",
["Desaturate Screen When Low"] = "低生命值时去饱和屏幕",
["Detection Range"] = "检测范围",
["Determines if additional levels past the max level can be displayed."] = "决定是否显示超出最高等级的额外等级。",
["Dev Mode"] = "开发者模式",
["Device"] = "设备",
["Die as the last Survivor for the first time"] = "首次作为最后一名幸存者死亡",
["Die at least once on each map"] = "每张地图至少死亡一次",
["Die within the first 20 seconds of a round"] = "在一回合的前 20 秒内死亡",
["Disable Being Killer"] = "禁用成为杀手",
["Disable EXP + Cash Notifs"] = "禁用经验 + 现金通知",
["Disables emote sound effects and ambience"] = "禁用表情音效和环境音",
["Disables most of the visual effects for emotes"] = "禁用表情的大部分视觉效果",
["Display Auras Without Highlights"] = "无高亮显示光环",
["Display Extra Levels"] = "显示额外等级",
["Displays developer tools on screen & some other stuff"] = "在屏幕上显示开发者工具及其他内容",
["Distance that you have to be from another player to view their nametag"] = "你需要与另一名玩家保持的距离才能查看其名字标签",
["Do A Flip!"] = "翻个跟头！",
["Do you want to close this window? You will not be able to open it again."] = "是否要关闭此窗口？你将无法再次打开它。",
["Drag Duration"] = "拖拽持续时间",
["Dusekkar"] = "Dusekkar",
["Duynam2988"] = "Duynam2988",
["E"] = "E",
["ESP"] = "透视",
["EXP Boost Time Left: "] = "经验加成剩余时间：",
["Elliot"] = "Elliot",
["Elliot Aimbot"] = "Elliot 自瞄",
["Elliot Script"] = "Elliot 脚本",
["Emote Camera"] = "表情相机",
["Emote Hands Disabled"] = "禁用表情手部",
["Emote Keybind"] = "表情键位",
["Emote SFX Disabled"] = "禁用表情音效",
["Emote Syncing"] = "表情同步",
["Emote VFX Disabled"] = "禁用表情视觉效果",
["Emote Volume"] = "表情音量",
["Emotes"] = "表情",
["Employee Of The Century"] = "世纪员工",
["Enable Aimbot"] = "启用自瞄",
["Enable Anti-Backstab"] = "启用反背刺",
["Enable Better Detection"] = "启用更好的检测",
["Enable Cinematic Text"] = "启用电影式文字",
["Enable HDT"] = "启用命中框拖拽",
["Enable Legacy Facing"] = "启用旧版朝向",
["Enable Lineblock"] = "启用线性格挡",
["Enable Ping Checker"] = "启用延迟检查器",
["Enable Punch Mobility"] = "启用出拳机动性",
["Enable Reverse"] = "启用反向",
["Enable Spoofer"] = "启用欺骗器",
["Engineer Builderman (Skin)"] = "工程师 Builderman（皮肤）",
["Enhanced Edition"] = "增强版",
["Epilepsy Mode"] = "癫痫模式",
["Equip"] = "装备",
["Esc + R"] = "Esc + R",
["Everything's Spinning..."] = "一切都在旋转...",
["Exploiting"] = "利用漏洞",
["FPS Counter"] = "帧数计数器",
["FREE"] = "免费",
["Face Killer During HDT"] = "命中框拖拽期间面向杀手",
["Facing Sensitivity"] = "朝向灵敏度",
["Field Of View"] = "视野范围",
["For opening & closing the emote menu (when it's able to be used)"] = "用于打开和关闭表情菜单（当可用时）",
["For the outcome is already decided."] = "因为结局已定。",
["For things like interacting with items, picking up stuff, opening doors, etc"] = "用于与物品互动、捡起东西、开门等操作",
["For things like slashes, activating items, etc."] = "用于挥砍、激活物品等操作",
["For toggling shift lock. Duh"] = "用于切换 Shift 锁定。显然",
["For using unique abilities as the killer/survivor"] = "用于作为杀手/幸存者使用独特技能",
["Forward Aerial"] = "向前空中",
["From Rags To Riches"] = "从贫到富",
["Full Roster"] = "完整名单",
["Fun"] = "趣味",
["Funnier Ragdolls"] = "更有趣的布娃娃",
["GET OVER HERE!"] = "过 来 这 里！",
["Gain Rate"] = "获取速率",
["Game"] = "游戏",
["General"] = "通用",
["Generator"] = "发电机",
["Generators"] = "发电机",
["Ghostburger"] = "幽灵汉堡",
["Global"] = "全局",
["Gluttonous Beast"] = "贪食野兽",
["Griefing"] = "恶意破坏",
["Guest 1337"] = "Guest 1337",
["Guest 666"] = "Guest 666",
["Guest1337"] = "Guest1337",
["HDT Mode"] = "命中框拖拽模式",
["HDT Visual (Beam)"] = "命中框拖拽视觉效果（光束）",
["Hacklord1x1x1x1 (Skin)"] = "Hacklord1x1x1x1（皮肤）",
["Happy Feet"] = "快乐脚丫",
["Have 4 or more status effects applied to you at once"] = "同时对你施加 4 个或以上状态效果",
["Head"] = "头部",
["Heal yourself back to full health while having less than 50% health during a round"] = "在一局中生命值低于 50% 时将自己治疗至满血",
["Health"] = "生命值",
["Health Display Type"] = "生命值显示类型",
["Hear his tale"] = "聆听他的故事",
["Height-Aware Aim"] = "高度感知瞄准",
["Hide Killer Wins"] = "隐藏杀手胜利次数",
["Hide Playtime"] = "隐藏游戏时间",
["Hide Survivor Wins"] = "隐藏幸存者胜利次数",
["Hides the amount of time that you've been playing Forsaken"] = "隐藏你玩 Forsaken 的总时长",
["Hides the amount of times you've won as Killer"] = "隐藏你作为杀手获胜的次数",
["Hides the amount of times you've won as Survivor"] = "隐藏你作为幸存者获胜的次数",
["Hides the hands in certain emotes"] = "隐藏某些表情中的手部",
["Hides the notifications that tell you when you earn cash and/or EXP"] = "隐藏告知你获得现金和/或经验的通知",
["Higher = snappier aim (14 default)"] = "数值越高 = 瞄准越干脆（默认 14）",
["Highlight Transparency"] = "高亮透明度",
["Hit Effects Enabled"] = "启用命中特效",
["Hit more dance moves till you're damned!\n+ Unlocks eight additional emote slots to fit in all your emotes.\n+ Dance with more of your purchased emotes so none are left out!"] = "跳更多舞步直到你完蛋！\n+ 解锁八个额外表情槽，容纳你所有的表情。\n+ 与你购买的更多表情共舞，不让任何一个落单！",
["Hitbox"] = "命中框",
["Hitbox Dragging (HDT)"] = "命中框拖拽",
["Hitbox Expander"] = "命中框扩大器",
["Hitbox X"] = "命中框 X",
["Hitbox Y"] = "命中框 Y",
["Hitbox Z (forward)"] = "命中框 Z（向前）",
["Hitmarkers Enabled"] = "启用命中标记",
["Hitsound ID"] = "命中音效 ID",
["Hitsounds Enabled"] = "启用命中音效",
["Hold the aim key to snap onto target (PC recommended)"] = "按住瞄准键吸附目标（推荐 PC 端）",
["Hold-to-Aim"] = "按住瞄准",
["How do I do the assist level 3"] = "如何完成辅助等级 3",
["How far the camera will sway when you move it around. Set to 0 to disable swaying"] = "移动相机时相机晃动的幅度。设为 0 可禁用晃动",
["How loud sound effects (gunshots, attacks, etc) are"] = "音效（枪声、攻击等）的音量",
["How loud sounds from emotes are"] = "表情音效的音量",
["How loud soundtracks (chase themes, ambience, etc) are"] = "原声带（追逐主题、环境音等）的音量",
["How loud the voicelines said by certain characters are"] = "特定角色语音的音量",
["How player health is displayed to you"] = "玩家生命值如何显示给你",
["How player nametags are displayed to you"] = "玩家名字标签如何显示给你",
["I Cast Upon Thee"] = "我向汝施法",
["I KNEW THAT DOOR HAD A LOCK ON IT!"] = "我就知道那扇门上有锁！",
["I Must Confess That I Feel Like A Monster"] = "我必须承认我感觉像个怪物",
["If you don't click then you can't spectate"] = "如果你不点击，就无法观战",
["In a full lobby, win as a Survivor without any deaths from your team"] = "在满员大厅中，作为幸存者获胜且队伍无一人死亡",
["Inappropriate Avatars"] = "不当头像",
["Infinite Stamina"] = "无限体力",
["Info"] = "信息",
["Interact Keybind"] = "互动键位",
["Interact with the cat in the lobby more than 15 times"] = "在大厅中与猫互动超过 15 次",
["Interface"] = "界面",
["Inventory"] = "背包",
["Invite Friends (+0% EXP)"] = "邀请好友（+0% 经验）",
["It's Just A Rumor"] = "这只是个谣言",
["Items"] = "物品",
["JD Digital Footprints"] = "JD 数字足迹",
["JOIN"] = "加入",
["Jane Doe"] = "Jane Doe",
["John Doe"] = "John Doe",
["Johnny, Johnny..."] = "Johnny, Johnny...",
["Join your friends who are playing Forsaken!"] = "加入正在玩 Forsaken 的好友！",
["Jumpscare"] = "跳跃惊吓",
["Keeps you from being put into matches when enabled"] = "启用时防止你被放入对局中",
["Key to hold when Hold-to-Aim is enabled"] = "启用按住瞄准时要按住的键",
["Keybinds"] = "键位绑定",
["Killer"] = "杀手",
["Killer Abilities"] = "杀手技能",
["Killer Losses: 0"] = "杀手失败次数：0",
["Killer Milestones"] = "杀手里程碑",
["Killer Specific"] = "杀手专属",
["Killer Stats"] = "杀手统计",
["Killer Wins: 0"] = "杀手胜利次数：0",
["Killers"] = "杀手列表",
["Killsound ID"] = "击杀音效 ID",
["Knockin' on Death's Door"] = "敲响死亡之门",
["LMS Music"] = "最后幸存者阶段音乐",
["Large Killer Transparent"] = "大型杀手透明",
["LeftControl"] = "左 Control",
["LeftShift"] = "左 Shift",
["Legacy"] = "旧版",
["Legacy Facing"] = "旧版朝向",
["Legit Speed"] = "合法速度",
["Lerp"] = "插值",
["Level 100"] = "等级 100",
["Lifeline"] = "生命线",
["Line Block"] = "线性格挡",
["Line Length"] = "线条长度",
["Line Pause"] = "线条暂停",
["Line Radius"] = "线条半径",
["Lineblock"] = "线性格挡",
["Lock Time (s)"] = "锁定时间（秒）",
["Locked"] = "已锁定",
["Look Duration (s)"] = "注视持续时间（秒）",
["Loss Rate"] = "损失速率",
["Luckiest Man Alive"] = "世上最幸运的人",
["Lunge Boost"] = "突进增强",
["Lunge Multiplier"] = "突进倍率",
["MLGChance (Skin)"] = "MLGChance（皮肤）",
["Main Ability Keybind"] = "主要技能键位",
["Maintained By Viper"] = "由 Viper 维护",
["Maintained by Viper"] = "由 Viper 维护",
["Make a Survivor leave the game within 15 seconds of attacking them (aka ragequit)"] = "让一名幸存者在被攻击后 15 秒内离开游戏（即怒退）",
["Makes all attack hitboxes visible to you"] = "使所有攻击命中框对你可见",
["Makes all player collision hitboxes visible to you"] = "使所有玩家碰撞命中框对你可见",
["Makes it so that you don't earn any Malice, thus lessening your chance of becoming the Killer"] = "使你不获得任何恶意值，从而降低你成为杀手的机会",
["Makes ragdolls a bit more broken (which makes them funnier in a lot of cases)"] = "使布娃娃更加破碎（在许多情况下更有趣）",
["Malice"] = "恶意值",
["Manual Drag"] = "手动拖拽",
["Map Header"] = "地图标题",
["Max Distance"] = "最大距离",
["Max Pool"] = "最大池",
["Medic Dusekkar (Skin)"] = "医疗兵 Dusekkar（皮肤）",
["Meet Jane Doe for the first time"] = "首次遇见 Jane Doe",
["Meet ozolog1’s best friend for the first time"] = "首次遇见 ozolog1 最好的朋友",
["Meow meow meow"] = "喵喵喵",
["Message Text"] = "消息文本",
["Message When Aim"] = "瞄准时消息",
["Middle"] = "中间",
["Minion & Ability ESP"] = "随从与技能透视",
["Mirror Chance (Skin)"] = "镜像 Chance（皮肤）",
["Misc"] = "杂项",
["Mode Guide"] = "模式指南",
["Model By: someone"] = "模型由：someone",
["Mold Girl"] = "霉菌女孩",
["Money"] = "金钱",
["More Info"] = "更多信息",
["Mother's Calling"] = "母亲的呼唤",
["MouseButton1"] = "鼠标左键",
["Multiplier"] = "倍率",
["Murphy's Law"] = "墨菲定律",
["Music"] = "音乐",
["Music Volume"] = "音乐音量",
["My Entire Skeleton"] = "我的整个骨架",
["Mystic Slasher (Skin)"] = "神秘 Slasher（皮肤）",
["Nametag Display Title 1"] = "名字标签显示标题 1",
["Nametag Display Title 2"] = "名字标签显示标题 2",
["Nametag Display Title 3"] = "名字标签显示标题 3",
["Nametag Display Type"] = "名字标签显示类型",
["Nametag Viewing Distance"] = "名字标签查看距离",
["Nametags Enabled"] = "启用名字标签",
["Natural Disaster Survival"] = "自然灾害生存",
["Net Worth: 885$"] = "净资产：885 美元",
["Net Worth: 925$"] = "净资产：925 美元",
["Network Ping"] = "网络延迟",
["Nlongdeptrai2k8"] = "Nlongdeptrai2k8",
["No HDT Cooldown"] = "无命中框拖拽冷却",
["Noclip"] = "穿墙",
["Noclip Only When Block Ready"] = "仅在格挡就绪时穿墙",
["Node Speed"] = "节点速度",
["Noli"] = "Noli",
["Noli — Void Rush Control"] = "Noli — 虚空冲锋控制",
["Noob"] = "Noob",
["Normal"] = "普通",
["Nosferatu"] = "Nosferatu",
["Not My First Time"] = "不是第一次",
["OHH, BABY A TRIPLE!"] = "哦，宝贝，三连！",
["Objectives Completed As Survivor: 2"] = "作为幸存者完成目标：2",
["On Hover"] = "悬停时",
["One Stone"] = "一石二鸟",
["Optimization"] = "优化",
["Original gameplay, but only having people with VC!"] = "原始玩法，但只有拥有语音聊天的人！",
["Owned"] = "已拥有",
["Owner's Setting Opinion"] = "所有者的设置意见",
["PC / Input"] = "PC / 输入",
["PLAY WITH FRIENDS"] = "与好友一起玩",
["Particles Enabled"] = "启用粒子效果",
["Personal Emotes Affected"] = "个人表情受影响",
["Pick up an item that was dropped by a dead Survivor"] = "捡起已故幸存者掉落的物品",
["Ping"] = "延迟",
["Ping Aim Preset"] = "延迟瞄准预设",
["Ping Checker"] = "延迟检查器",
["Pizza Throw Force"] = "披萨投掷力度",
["PizzaDeliveryRig — orange highlight"] = "PizzaDeliveryRig — 橙色高亮",
["Platform Spoofer"] = "平台欺骗器",
["Play Forsaken for the first time"] = "首次玩 Forsaken",
["Play as John Doe on March 18th"] = "在 3 月 18 日扮演 John Doe",
["Play as Slasher on Friday the 13th"] = "在 13 号星期五扮演 Slasher",
["Player Points ($): 385$"] = "玩家点数（$）：385 美元",
["Player Points ($): 425$"] = "玩家点数（$）：425 美元",
["Players"] = "玩家",
["Please click one of the buttons"] = "请点击其中一个按钮",
["Pre-Delay (s)"] = "预延迟（秒）",
["Prediction Forward"] = "向前预测",
["Prediction Mode"] = "预测模式",
["Prediction Studs"] = "预测长度单位",
["Prediction Time (s)"] = "预测时间（秒）",
["Prediction Turn"] = "转向预测",
["Prediction Value"] = "预测值",
["Preload All Assets (HEAVY)"] = "预加载所有资源（较重）",
["Premium Builder's Club"] = "高级建设者俱乐部",
["Press to go back"] = "按此返回",
["Privacy"] = "隐私",
["Pronouns"] = "人称代词",
["Punch"] = "出拳",
["Punch Mobility"] = "出拳机动性",
["Punch Prediction"] = "出拳预测",
["Purchase"] = "购买",
["Purified I"] = "净化 I",
["Put Dispenser Here!"] = "把补给器放在这里！",
["Q"] = "Q",
["QUICK PLAY"] = "快速游戏",
["Quickest Thinker"] = "最快思考者",
["R"] = "R",
["R$ Spent: 0 R$"] = "已花费 R$：0 R$",
["Ragdoll Limit"] = "布娃娃限制",
["Range Mode"] = "范围模式",
["Rank Title Enabled"] = "启用等级称号",
["Reach Lvl 100 on 007n7"] = "将 007n7 升至 100 级",
["Reach Lvl 100 on 1x1x1x1"] = "将 1x1x1x1 升至 100 级",
["Reach Lvl 100 on Builderman"] = "将 Builderman 升至 100 级",
["Reach Lvl 100 on Chance"] = "将 Chance 升至 100 级",
["Reach Lvl 100 on Dusekkar"] = "将 Dusekkar 升至 100 级",
["Reach Lvl 100 on Elliot"] = "将 Elliot 升至 100 级",
["Reach Lvl 100 on Guest 1337"] = "将 Guest 1337 升至 100 级",
["Reach Lvl 100 on Guest666"] = "将 Guest666 升至 100 级",
["Reach Lvl 100 on Jane Doe"] = "将 Jane Doe 升至 100 级",
["Reach Lvl 100 on John Doe"] = "将 John Doe 升至 100 级",
["Reach Lvl 100 on Noli"] = "将 Noli 升至 100 级",
["Reach Lvl 100 on Noob"] = "将 Noob 升至 100 级",
["Reach Lvl 100 on Nosferatu"] = "将 Nosferatu 升至 100 级",
["Reach Lvl 100 on Shedletsky"] = "将 Shedletsky 升至 100 级",
["Reach Lvl 100 on Slasher"] = "将 Slasher 升至 100 级",
["Reach Lvl 100 on Taph"] = "将 Taph 升至 100 级",
["Reach Lvl 100 on Two Time"] = "将 Two Time 升至 100 级",
["Reach Lvl 100 on Veeronica"] = "将 Veeronica 升至 100 级",
["Reach Lvl 100 on c00lkidd"] = "将 c00lkidd 升至 100 级",
["Remote Fire Delay (s)"] = "远程发射延迟（秒）",
["Require Throw Animation"] = "需要投掷动画",
["Respawning Elsewhere"] = "在别处重生",
["Reverse"] = "反向",
["Reverse Block"] = "反向格挡",
["Reward:"] = "奖励：",
["Robloxia's Strongest Soldier"] = "Robloxia 最强士兵",
["Robux"] = "Robux",
["Rotation Smoothing"] = "旋转平滑",
["Rules"] = "规则",
["S.F.O.T.H."] = "S.F.O.T.H.",
["SFX Volume"] = "音效音量",
["Samm"] = "Samm",
["Screen Shaking Enabled"] = "启用屏幕震动",
["Script Credits"] = "脚本致谢",
["Segments"] = "段数",
["Sensitive Music Mode"] = "敏感音乐模式",
["Sensitive SFX Mode"] = "敏感音效模式",
["Sentinel"] = "哨兵",
["Sentinels"] = "哨兵们",
["Setting"] = "设置",
["Settings"] = "设置",
["Setup Generators"] = "设置发电机",
["Severe And Continuous"] = "严重且持续",
["Shake Screen When Low"] = "低生命值时震动屏幕",
["Shedletsky"] = "Shedletsky",
["Shedletsky (just use hitbox lol)"] = "Shedletsky（直接用命中框，哈哈）",
["Shift Lock Keybind"] = "Shift 锁定键位",
["Shop"] = "商店",
["Show Chat Logs"] = "显示聊天记录",
["Show HDT Range"] = "显示命中框拖拽范围",
["Show Pizza Arc"] = "显示披萨弧线",
["Show Vision Cone"] = "显示视野锥体",
["Show Vision Range"] = "显示视野范围",
["Shows your stamina as a number beneath the crosshair"] = "在准星下方以数字显示你的体力值",
["Sixer — Air Strafe"] = "Sixer — 空中扫射",
["Skins"] = "皮肤",
["Skip Intro Cutscenes"] = "跳过开场动画",
["Skips through the intro cutscenes that killers have"] = "跳过杀手的开场动画",
["Slasher"] = "Slasher",
["Slateskin Potion"] = "石板皮肤药水",
["Smart Delay"] = "智能延迟",
["Smart Sound Cache (Memory Efficiency)"] = "智能声音缓存（内存效率）",
["Smart Sound Cache Time"] = "智能声音缓存时间",
["Smooth Speed"] = "平滑速度",
["Sparkly Clean"] = "闪亮洁净",
["Spectate"] = "观战",
["Spin Duration"] = "旋转持续时间",
["Spoof Usernames"] = "伪装用户名",
["Sprint Keybind"] = "冲刺键位",
["Stacked"] = "叠加",
["Stagger (s)"] = "踉跄时间（秒）",
["Stamina"] = "体力值",
["Start Distance"] = "起始距离",
["Stats"] = "统计数据",
["Status"] = "状态",
["Step Distance"] = "步进距离",
["Stop Emoting"] = "停止表情",
["Strength"] = "强度",
["Supports"] = "支援",
["Survivalist I"] = "生存专家 I",
["Survivalist II"] = "生存专家 II",
["Survivalist III"] = "生存专家 III",
["Survivalist IV"] = "生存专家 IV",
["Survivalist V"] = "生存专家 V",
["Survive a round with less than 10% health"] = "以低于 10% 的生命值存活一局",
["Survive at least once on each map"] = "每张地图至少存活一次",
["Survivor Losses: 1"] = "幸存者失败次数：1",
["Survivor Milestones"] = "幸存者里程碑",
["Survivor Name"] = "幸存者名称",
["Survivor Specific"] = "幸存者专属",
["Survivor Stats"] = "幸存者统计",
["Survivor UI Display Type"] = "幸存者界面显示类型",
["Survivor UI Enabled"] = "启用幸存者界面",
["Survivor Wins: 1"] = "幸存者胜利次数：1",
["Survivor Wins: 2"] = "幸存者胜利次数：2",
["Survivor/Killer Name"] = "幸存者/杀手名称",
["Survivor/Killer Quote goes here"] = "幸存者/杀手语录在此",
["Survivors"] = "幸存者",
["Switch Distance (Smart)"] = "切换距离（智能）",
["T"] = "T",
["TVTime (Emote)"] = "电视时间（表情）",
["Target Mode"] = "目标模式",
["Team Effort"] = "团队合作",
["Teaming"] = "组队",
["Tester's Setting Opinion"] = "测试者的设置意见",
["Text Content"] = "文本内容",
["The Masked Brute"] = "蒙面蛮兵",
["The amount of ragdolls that can be present at once"] = "同时存在的布娃娃数量上限",
["The amount of time if the smart cache is enabled until a reference is cleaned up while not in use."] = "启用智能缓存后，未使用的引用被清理前的等待时间。",
["The first thing displayed on a nametag"] = "名字标签上显示的第一项内容",
["The key that you have to hold in order to sprint"] = "你需要按住才能冲刺的键",
["The original gameplay of Forsaken."] = "Forsaken 的原始玩法。",
["The part that the camera locks onto during an emote"] = "表情期间相机锁定的部位",
["The second thing displayed on a nametag"] = "名字标签上显示的第二项内容",
["The sound ID for the hitsound that plays"] = "播放的命中音效的 ID",
["The sound ID to play when you kill a Survivor"] = "击杀幸存者时播放的音效 ID",
["The style of how living/dead survivors are displayed as when in a match"] = "对局中存活/死亡幸存者的显示样式",
["The texture ID for the crosshair, if enabled"] = "准星的纹理 ID（如果启用）",
["The third thing displayed on a nametag"] = "名字标签上显示的第三项内容",
["TheY'Re sUfFErINg BECAusE of YoU."] = "他 们 在 受 苦 是 因 为 你。",
["TheY're SuFFERiNG BeCausE OF YOU."] = "他 们 在 受 苦 是 因 为 你。",
["There is nothing either good or bad, but thinking makes it so..."] = "世事本无好坏，皆因思想使然...",
["They'RE SuffERinG bECaUsE oF yoU."] = "他 们 在 受 苦 是 因 为 你。",
["They/Them"] = "他们/她们",
["This tab is Empty"] = "此标签页为空",
["Time for some murder >:D"] = "是时候杀人了 >:D",
["Timer Position"] = "计时器位置",
["Toggle: Hallucination"] = "切换：幻觉",
["Toggle: Slowness"] = "切换：减速",
["Toggle: Visual Effects"] = "切换：视觉效果",
["Toggles automatic emote syncing"] = "切换自动表情同步",
["Too Good"] = "太厉害了",
["Total Kills: 0"] = "总击杀数：0",
["Toxicity"] = "毒性",
["Track"] = "曲目",
["Tragic Accident"] = "悲剧事故",
["Tricked Ya!"] = "骗到你啦！",
["Trigger Radius"] = "触发半径",
["True Survivalist"] = "真正的生存专家",
["TwoTime"] = "TwoTime",
["UI Functions"] = "界面功能",
["Ultrakill Chance (Skin)"] = "究极杀戮 Chance（皮肤）",
["Ultrakill Guest (Skin)"] = "究极杀戮 Guest（皮肤）",
["Unidentified Foe"] = "身份不明的敌人",
["Unlikely Winner"] = "黑马胜者",
["Unlikely Winner 2: Electric Boogaloo"] = "黑马胜者 2：电气布加卢",
["Unload Script"] = "卸载脚本",
["Unlock every purchasable character"] = "解锁所有可购买角色",
["Unrelenting Force"] = "无情力量",
["Username"] = "用户名",
["V1PR"] = "V1PR",
["V1PR / Glovsaken"] = "V1PR / Glovsaken",
["V1PRBLOCK"] = "V1PRBLOCK",
["V1PRSTAB"] = "V1PRSTAB",
["V1PRWARE"] = "V1PRWARE",
["VC"] = "语音聊天",
["VIP Title Enabled"] = "启用 VIP 称号",
["Veeronica"] = "Veeronica",
["Veiled Eyes"] = "蒙蔽的双眼",
["Velocity"] = "速度",
["Verify Facing Check"] = "验证朝向检查",
["Version: 61 (Latest)"] = "版本：61（最新）",
["Vignette When Damaged"] = "受伤时显示暗角",
["Visible Attack Hitboxes"] = "可见的攻击命中框",
["Visible Collision Hitboxes"] = "可见的碰撞命中框",
["Vision Angle"] = "视野角度",
["Vision Range"] = "视野范围",
["Visual"] = "视觉",
["Vlad The Impaler"] = "穿刺公弗拉德",
["Voiceline Volume"] = "语音音量",
["WHAT THE- BOOOM!!"] = "什么鬼——轰！！",
["Wasted Potential"] = "浪费的潜力",
["Wayward Taph (Skin)"] = "任性 Taph（皮肤）",
["Welcome To Hell"] = "欢迎来到地狱",
["Well... This sucks..."] = "好吧... 这糟透了...",
["What a Shame."] = "真可惜。",
["Whether or not a crosshair is displayed at the centre of the screen (Mobile)"] = "是否在屏幕中心显示准星（手机端）",
["Whether or not a vignette appears whenever you receive damage and/or when you're <50% HP"] = "是否在受到伤害和/或生命值低于 50% 时显示暗角",
["Whether or not actions will cause screen shaking if possible"] = "是否在可能的情况下让操作引起屏幕震动",
["Whether or not all living/dead survivors in a match will be displayed"] = "是否显示对局中所有存活/死亡的幸存者",
["Whether or not hit indicator effects will play upon successfully hitting & killing survivors"] = "是否在成功命中及击杀幸存者时播放命中指示器特效",
["Whether or not hit sounds play upon landing a hit on someone"] = "是否在命中他人时播放命中音效",
["Whether or not hitmarkers are displayed over the heads of people you deal damage to"] = "是否在你造成伤害的目标头顶显示命中标记",
["Whether or not hitmarkers display the total damage dealt instead of individual damage dealt"] = "命中标记是否显示造成的总伤害而非单次伤害",
["Whether or not ingame particles will be rendered on your screen"] = "是否在你的屏幕上渲染游戏内粒子效果",
["Whether or not nametags show above ingame survivors"] = "是否在游戏内幸存者头顶显示名字标签",
["Whether or not your VIP tag shows up in chat"] = "你的 VIP 标签是否显示在聊天中",
["Whether or not your group rank tag shows up in chat"] = "你的群组等级标签是否显示在聊天中",
["Whether or not your own emotes will be affected by your preferred emote settings"] = "你自己的表情是否会受你偏好的表情设置影响",
["Whether or not your screen becomes desaturated when you reach <50% HP"] = "当你的生命值低于 50% 时屏幕是否去饱和",
["Whether or not your screen starts to shake when you reach <50% HP"] = "当你的生命值低于 50% 时屏幕是否开始震动",
["Whether you would like the map header to be displayed when the round starts."] = "是否在回合开始时显示地图标题。",
["Whether you would like to remove sounds appended to the cache after a certain amount of time"] = "是否在一定时间后从缓存中移除添加的声音",
["White Pumpkin Slasher (Skin)"] = "白南瓜 Slasher（皮肤）",
["Win 10 rounds as a Survivor"] = "作为幸存者赢得 10 回合",
["Win 100 rounds as a Survivor"] = "作为幸存者赢得 100 回合",
["Win 1000 rounds as a Survivor"] = "作为幸存者赢得 1000 回合",
["Win 125 rounds as a Killer"] = "作为杀手赢得 125 回合",
["Win 250 rounds as a Killer"] = "作为杀手赢得 250 回合",
["Win 250 rounds as a Survivor"] = "作为幸存者赢得 250 回合",
["Win 5 rounds as a Killer"] = "作为杀手赢得 5 回合",
["Win 50 rounds as a Killer"] = "作为杀手赢得 50 回合",
["Win 500 rounds as a Killer"] = "作为杀手赢得 500 回合",
["Win 500 rounds as a Survivor"] = "作为幸存者赢得 500 回合",
["Win as the last Survivor for the first time"] = "首次作为最后一名幸存者获胜",
["Wipe a full lobby as the Killer"] = "作为杀手团灭满员大厅",
["With this option on you will preload everything that is replicated from the server (including skins), this could result in longer loading times if your device is on the lower-end. Enable with caution"] = "开启此选项后，你将预加载服务器复制的所有内容（包括皮肤），如果你的设备性能较低，可能会导致加载时间变长。请谨慎启用",
["Wrong Address"] = "错误地址",
["YOU DON'T GET TO JUDGE ME!"] = "你 没 资 格 评 判 我！",
["YOUR cOWarDICE wILl COsT LiVes."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["YOUr COwardiCE wIll COSt lIvES."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["YOuR CoWaRdICe wILL cOst LivES."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["YOuR cOwARDIce WIlL COst liveS."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["YOur CoWarDIce wilL cosT LiveS."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["YOur CowarDICe WiLl cost liVeS."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["YOur cOWarDiCE WIll coST LIVES."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["Years in the future, but not many..."] = "未来几年，但不会太久...",
["YoUR CoWARDICE WILl CoSt LIvES."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["YoUR cOwArdice wIll cosT LiVeS."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["YoUr COWarDICE WIll cOst LIvES."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["YoUr Cowardice wIlL cOst LIveS."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["YoUr cOWArDICe WilL COST lIvEs."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["YoUr cOWardice wilL cOst liVEs."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["Yoink!"] = "拿来吧你！",
["You're Fired"] = "你被解雇了",
["You're Quick as Hell!"] = "你真是太快了！",
["YouR COwArDicE wIll cOSt LiVes."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["Your CoWaRdIcE wilL COSt lIVeS."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["Your CoWaRdiCe will cosT LiVES."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["Your CowArDiCe WiLl CosT livES."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["Your camera's FOV"] = "你的相机视野范围",
["[+PARRY]"] = "[+招架]",
["c00lkidd"] = "c00lkidd",
["c00lkidd Pizza Bots"] = "c00lkidd 披萨机器人",
["c00lkidd — Dash Turn"] = "c00lkidd — 冲刺转向",
["ckan_2k13"] = "ckan_2k13",
["duyan873332"] = "duyan873332",
["kenichi_vaporous"] = "kenichi_vaporous",
["kenichi_vaporous (You)"] = "kenichi_vaporous（你）",
["nuh uh"] = "不 不",
["tHEY'RE sufFERINg bEcause Of you."] = "他 们 在 受 苦 是 因 为 你。",
["tHEy'Re sufFerINg BECause of YOu."] = "他 们 在 受 苦 是 因 为 你。",
["tHeY'RE SUFFeRIng BecausE OF yoU."] = "他 们 在 受 苦 是 因 为 你。",
["tHeY're SUFferiNG BECausE of yOU."] = "他 们 在 受 苦 是 因 为 你。",
["tHey'RE sUFFERINg BecAUSE OF You."] = "他 们 在 受 苦 是 因 为 你。",
["tHey'RE sUffErinG BeCAuSE of YOU."] = "他 们 在 受 苦 是 因 为 你。",
["tHey'Re sUFfErinG BECauSe of yOU."] = "他 们 在 受 苦 是 因 为 你。",
["tHey'Re sUFfeRing bECauSE of YOU."] = "他 们 在 受 苦 是 因 为 你。",
["tHey'rE sUffERIng BecaUSE of YoU."] = "他 们 在 受 苦 是 因 为 你。",
["tHey'rE suFFeRiNg BEcaUse OF yOu."] = "他 们 在 受 苦 是 因 为 你。",
["tHey'rE suffEriNg BECausE Of yOU."] = "他 们 在 受 苦 是 因 为 你。",
["tHey're SUFFeRInG beCauSe of YOu."] = "他 们 在 受 苦 是 因 为 你。",
["tHey're sUffEring BecausE Of You."] = "他 们 在 受 苦 是 因 为 你。",
["taolathangngu624"] = "taolathangngu624",
["thEY'RE sUFfErinG beCauSe Of yOU."] = "他 们 在 受 苦 是 因 为 你。",
["thEY'RE suFFErinG bEcaUSe of You."] = "他 们 在 受 苦 是 因 为 你。",
["thEY'RE suFferinG becAuSe oF yOU."] = "他 们 在 受 苦 是 因 为 你。",
["thEY'RE sufFErInG BEcause of You."] = "他 们 在 受 苦 是 因 为 你。",
["thEY'RE suffERiNG BEcausE oF yOu."] = "他 们 在 受 苦 是 因 为 你。",
["thEY're SUFFErINg BeCauSE oF YOu."] = "他 们 在 受 苦 是 因 为 你。",
["thEY're suFfErIng BecaUSe oF YoU."] = "他 们 在 受 苦 是 因 为 你。",
["thEy'RE SUfFeRinG BeCaUSe Of yOU."] = "他 们 在 受 苦 是 因 为 你。",
["thEy'rE SUFfeRiNG BEcause of YOU."] = "他 们 在 受 苦 是 因 为 你。",
["theY'RE SuffeRinG BeCauSe oF you."] = "他 们 在 受 苦 是 因 为 你。",
["theY'Re sUFfERInG BEcAusE Of yoU."] = "他 们 在 受 苦 是 因 为 你。",
["theY'Re suFferIng bECAUSE Of you."] = "他 们 在 受 苦 是 因 为 你。",
["they'rE suFFEriNG BEcauSe oF you."] = "他 们 在 受 苦 是 因 为 你。",
["they're suFFERINg becaUSE Of yoU."] = "他 们 在 受 苦 是 因 为 你。",
["they're suFferIng beCAUsE of YOU."] = "他 们 在 受 苦 是 因 为 你。",
["yOUR COWaRdiCE wiLL coST lIvES."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["yOUR COwardice WiLL CosT LIVeS."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["yOUR CowaRDice Will CoST LivES."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["yOUR cOWardIcE WilL cost LIveS."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["yOUr coWaRDIce WiLl cOst LivES."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["yOuR COWarDIcE WIll CosT LiVes."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["yOuR COWarDIce wilL CoST LivEs."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["yOuR cowArDICE wIll CoSt LiVes."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["yOur CowArdICE wILl cost LIVEs."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["yoUr COWardice wiLl CosT lIVEs."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["yoUr COwARdICE wIll cosT LIVeS."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["yoUr coWArDicE WIlL COsT liVeS."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["yoUr coWaRdIce wILl Cost LIves."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["youR coWARDIce wILl cOsT lIVEs."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["youR coWArDiCE WiLL CoST liVEs."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["youR cowaRdIcE WiLL COsT LIvEs."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["your cOWaRdIcE will cOsT lives."] = "你 的 懦 弱 将 付 出 生 命 的 代 价。",
["ÜberCharge"] = "超级冲锋",
}

local function translateText(text)
    if not text or type(text) ~= "string" then return text end
    
    if Translations[text] then
        return Translations[text]
    end
    
    for en, cn in pairs(Translations) do
        if text:find(en) then
            return text:gsub(en, cn)
        end
    end
    
    return text
end

local function setupTranslationEngine()
    local success, err = pcall(function()
        local oldIndex = getrawmetatable(game).__newindex
        setreadonly(getrawmetatable(game), false)
        
        getrawmetatable(game).__newindex = newcclosure(function(t, k, v)
            if (t:IsA("TextLabel") or t:IsA("TextButton") or t:IsA("TextBox")) and k == "Text" then
                v = translateText(tostring(v))
            end
            return oldIndex(t, k, v)
        end)
        
        setreadonly(getrawmetatable(game), true)
    end)
    
    if not success then
        warn("元表劫持失败:", err)
       
        local translated = {}
        local function scanAndTranslate()
            for _, gui in ipairs(game:GetService("CoreGui"):GetDescendants()) do
                if (gui:IsA("TextLabel") or gui:IsA("TextButton") or gui:IsA("TextBox")) and not translated[gui] then
                    pcall(function()
                        local text = gui.Text
                        if text and text ~= "" then
                            local translatedText = translateText(text)
                            if translatedText ~= text then
                                gui.Text = translatedText
                                translated[gui] = true
                            end
                        end
                    end)
                end
            end
            
            local player = game:GetService("Players").LocalPlayer
            if player and player:FindFirstChild("PlayerGui") then
                for _, gui in ipairs(player.PlayerGui:GetDescendants()) do
                    if (gui:IsA("TextLabel") or gui:IsA("TextButton") or gui:IsA("TextBox")) and not translated[gui] then
                        pcall(function()
                            local text = gui.Text
                            if text and text ~= "" then
                                local translatedText = translateText(text)
                                if translatedText ~= text then
                                    gui.Text = translatedText
                                    translated[gui] = true
                                end
                            end
                        end)
                    end
                end
            end
        end
        
        local function setupDescendantListener(parent)
            parent.DescendantAdded:Connect(function(descendant)
                if descendant:IsA("TextLabel") or descendant:IsA("TextButton") or descendant:IsA("TextBox") then
                    task.wait(0.1)
                    pcall(function()
                        local text = descendant.Text
                        if text and text ~= "" then
                            local translatedText = translateText(text)
                            if translatedText ~= text then
                                descendant.Text = translatedText
                            end
                        end
                    end)
                end
            end)
        end
        
        pcall(setupDescendantListener, game:GetService("CoreGui"))
        local player = game:GetService("Players").LocalPlayer
        if player and player:FindFirstChild("PlayerGui") then
            pcall(setupDescendantListener, player.PlayerGui)
        end
        
        while true do
            scanAndTranslate()
            task.wait(3)
        end
    end
end

task.wait(2)

setupTranslationEngine()

local success, err = pcall(function()
--这下面填加载外部脚本
loadstring(game:HttpGet("https://pastebin.com/raw/zH9Extzk"))()

end)

if not success then
    warn("加载失败:", err)
end
